version: '3.7'
services:
  database:
    restart: always
    image: postgres:13.0-alpine
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: Hello123@
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: always
    env_file: test.env
    environment:
      GIN_MODE: debug
    networks:
      - default
    ports:
      - "8080:8080"